language: java
jdk:
- oraclejdk7
deploy:
  provider: openshift
  user: satspeedy@hotmail.com
  password:
    secure: glHSj3JcjmagmyN3bwbhszG3EvchJfMb/kaR2wAUK6dCx8zsrIsOel8PBBzTKjPLJu594dpe3M8EjD0I69+TZdQX43uevh/sGYO7YoK+X9nYzSteBWa6dMqSK67pCyYBFlAMJ9/hpg2g9wVVeWUjIltyDSNkCkFZC/vqFc+uEo8=
  app: scheckcheck
  domain: satspeedy
  on:
    repo: satspeedy/scheckcheck
after_success:
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git add --all
- git commit -am "Travis change"
